export default {
  overview: {
    labels: { mileage: 'Milieage(upto)', engine: 'Engine(upto)', BHP: 'BHP', transmission: 'Transmission', seats: 'Seats', serviceCost: 'Service Cost' },
    mileage: '18.6',
    engine: '1197',
    BHP: 81.86,
    transmission: 'Manual',
    seats: '5',
    serviceCost: 2562,
  },
  keySpecifications: {
    labels: {
      ARAIMileage: 'ARAI Mileage',
      fuelType: 'Fuel Type',
      engineDisplacement: 'Engine Displacement',
      maxPower: 'Max Power',
      maxTorque: 'Max Tourqe',
      seatingCapacity: 'Seat Capacity',
      transmissionType: 'Transmission Type',
      bootSpace: 'Boot Space',
      fuelTankCapacity: 'Fuel Tank Capacity',
      bodyType: 'Body Type',
      serviceCost: 'Service Cost',
    },
    name: 'Mahindra xuv 300 w4 pet 5str',
    price: 1500000,
    ARAIMileage: 22.54,
    fuelType: 'Diesel',
    engineDisplacement: 1396,
    maxPower: 88.76,
    maxTourque: '224nm@1500-2750rpm',
    seatingCapacity: 5,
    transmissionType: 'Manual',
    bootSpace: 285,
    fuelTankCapacity: 40,
    bodyType: 'Hatchback',
    serviceCost: 4012,
  },
  keyFeatures: {
    powerSteering: 1,
    powerWindowFront: 1,
    antiLockBrakingSystem: 1,
    airConditioner: 0,
    driverAirbag: 1,
    passengerAirbag: 0,
    automaticClimateControl: 1,
    fogLightsFront: 1,
    alloyWheels: 1,
  },

  specifications: {
    'Engine and Transmission': {
      engineType: 'U2 CRDI Diesel Engine',
      displacement: 1396,
      maxPower: '88.76bhp@4000rpm',
      maxTorque: '224nm@1500-2750rpm',
      noOfCylinder: 4,
      valvesPerCylinder: 4,
      valveConfiguration: 'DOHC',
      fuelSupplySystem: 'CRDI',
      turboCharger: 0,
      superCharge: 0,
      transmissionType: 'Manual',
      gearBox: 6,
      driveType: 'FWD',
    },
    'Fuel & Performance': {
      fuelType: 'Diesel',
      mileage: 22.54,
      fuelTankCapacity: 40,
      topSpeed: 170,
    },
    'Suspension, Steering & Brakes': {
      frontSuspension: 'McPherson Strut with Coil Spring',
      rearSuspension: 'Coupled Torsion Beam Axle with Coil Spring',
      shockAbsorbersType: 'Gas Filled',
      steeringType: 'Power',
      steeringColumn: 'Tilt & Telescopic',
      steeringGearType:	'Rack & Pinion',
      turningRadius: 5.2,
      frontBrakeType: 'Disc',
      rearBrakeType: 'Drum',
    },
    'Dimensions & Capacity': {
      seatingCapacity: 5,
      groundClearanceUnladen: 170,
      wheelBase: 2570,
      noOfDoors: 55,
    },
    'Comfort & Convenience': {
      powerSteering: null,
      powerWindowsFront: null,
      powerWindowsRear: null,
      airConditioner: null,
      heater: null,
      adjustableSteering: null,
    },
    Interior: {
      tachometer: null,
      electronicMultiTripmeter: null,
      digitalClock: null,
      cigaretteLighter: null,
      digitalOdometer: null,
      heightAdjustableDriverSeat: null,
    },
    Exterior: {
      adjustableHeadlights: null,
      fogLightsFront: null,
      fogLightsRear: null,
      exteriorRearViewMirror: null,
      wheelCovers: null,
      alloyWheelSize: null,
      roofCarrier: null,
      outsideRearViewMirrorTurnIndicators: null,
    },
    Safety: {
      antiLockBrakingSystem: null,
      centralLocking: null,
      antiTheftAlarm: null,
      noofAirbags: 6,
    },
    'Entertainment & Communication': {
      DVDPlayer: null,
      audioSystemRemoteControl: null,
      Integrated2DINAudio: null,
      'USB&Auxiliaryinput': null,
      bluetoothConnectivity: null,
      touchScreen: null,
      connectivity: 'Android Auto,Apple CarPlay,Mirror Link',
    },
  },
};
