export default {
  overview: {
    labels: { mileage: 'Milieage(upto)', engine: 'Engine(upto)', BHP: 'BHP', transmission: 'Transmission', seats: 'Seats', serviceCost: 'Service Cost' },
    mileage: '18.6',
    engine: '1197',
    BHP: 81.86,
    transmission: 'Manual',
    seats: '5',
    serviceCost: 2562,
  },
  keySpecifications: {
    labels: {
      ARAIMileage: 'ARAI Mileage',
      fuelType: 'Fuel Type',
      engineDisplacement: 'Engine Displacement',
      maxPower: 'Max Power',
      maxTorque: 'Max Tourqe',
      seatingCapacity: 'Seat Capacity',
      transmissionType: 'Transmission Type',
      bootSpace: 'Boot Space',
      fuelTankCapacity: 'Fuel Tank Capacity',
      bodyType: 'Body Type',
      serviceCost: 'Service Cost',
    },
    name: 'Mahindra xuv 300 w4 pet 5str',
    price: 1500000,
    ARAIMileage: 22.54,
    fuelType: 'Diesel',
    engineDisplacement: 1396,
    maxPower: 88.76,
    maxTourque: '224nm@1500-2750rpm',
    seatingCapacity: 5,
    transmissionType: 'Manual',
    bootSpace: 285,
    fuelTankCapacity: 40,
    bodyType: 'Hatchback',
    serviceCost: 4012,
  },
  keyFeatures: {
    labels: {
      powerSteering: 'Power Steering',
      powerWindowFront: 'Power Window Front',
      antiLockBrakingSystem: 'Anti Lock Braking System',
      airConditioner: 'Air Conditioner',
      driverAirbag: 'Driver Airbag',
      passengerAirbag: 'Passenger Airbag',
      automaticClimateControl: 'Automatic Climate Control',
      fogLightsFront: 'Fog Lights Front',
      alloyWheels: 'Alloy Wheels',
    },
    powerSteering: 1,
    powerWindowFront: 1,
    antiLockBrakingSystem: 1,
    airConditioner: 0,
    driverAirbag: 1,
    passengerAirbag: 0,
    automaticClimateControl: 1,
    fogLightsFront: 1,
    alloyWheels: 1,
  },

  specifications: {
    'Engine and Transmission': {
      labels: {
        engineType: 'Engine Type',
        displacement: 'Displacement',
        maxPower: 'Max Power',
        maxTorque: 'Max Torque',
        noOfCylinder: 'No Of Cylinder',
        valvesPerCylinder: 'Valves Per Cylinder',
        valveConfiguration: 'Valve Configuration',
        fuelSupplySystem: 'Fuel Supp1ly System',
        turboCharger: 'Turbo Charger',
        superCharge: 'SuperCharge',
        transmissionType: 'Transmission Type',
        gearBox: 'Gear Box',
        driveType: 'Drive Type',
      },
      engineType: 'U2 CRDI Diesel Engine',
      displacement: 1396,
      maxPower: '88.76bhp@4000rpm',
      maxTorque: '224nm@1500-2750rpm',
      noOfCylinder: 4,
      valvesPerCylinder: 4,
      valveConfiguration: 'DOHC',
      fuelSupplySystem: 'CRDI',
      turboCharger: 0,
      superCharge: 0,
      transmissionType: 'Manual',
      gearBox: 6,
      driveType: 'FWD',
    },
    'Fuel & Performance': {
      labels: {
        fuelType: 'Fuel Type',
        mileage: 'Mileage',
        fuelTankCapacity: 'Fuel Tank Capacity',
        topSpeed: 'TopSpeed',
      },
      fuelType: 'Diesel',
      mileage: 22.54,
      fuelTankCapacity: 40,
      topSpeed: 170,
    },
    'Suspension, Steering & Brakes': {
      labels: {
        frontSuspension: 'Front Suspension',
        rearSuspension: 'Rear Suspension',
        shockAbsorbersType: 'Shock Absorbers Type',
        steeringType: 'Steering Type',
        steeringColumn: 'Steering Column',
        steeringGearType: 'Steering Gear Type',
        turningRadius: 'Turning Radius',
        frontBrakeType: 'Front Brake Type',
        rearBrakeType: 'Rear Brake Type',
      },
      frontSuspension: 'McPherson Strut with Coil Spring',
      rearSuspension: 'Coupled Torsion Beam Axle with Coil Spring',
      shockAbsorbersType: 'Gas Filled',
      steeringType: 'Power',
      steeringColumn: 'Tilt & Telescopic',
      steeringGearType:	'Rack & Pinion',
      turningRadius: 5.2,
      frontBrakeType: 'Disc',
      rearBrakeType: 'Drum',
    },
    'Dimensions & Capacity': {
      labels: {
        seatingCapacity: 'Seating Capacity',
        groundClearanceUnladen: 'Ground Clearance Unladen',
        wheelBase: 'Wheel Base',
        noOfDoors: 'No Of Doors',
      },
      seatingCapacity: 5,
      groundClearanceUnladen: 170,
      wheelBase: 2570,
      noOfDoors: 55,
    },
    'Comfort & Convenience': {
      labels: {
        powerSteering: 'Power Steering',
        powerWindowsFront: 'Power WindowFront',
        powerWindowsRear: 'Power Windows Rear',
        airConditioner: 'Air Conditioner',
        heater: 'Heater',
        adjustableSteering: 'Adjustable Steering',
      },
      powerSteering: null,
      powerWindowsFront: null,
      powerWindowsRear: null,
      airConditioner: null,
      heater: null,
      adjustableSteering: null,
    },
    Interior: {
      labels: {
        tachometer: 'Tachometer',
        electronicMultiTripmeter: 'Electronic Multi Tripmeter',
        digitalClock: 'Digital Clock',
        cigaretteLighter: 'Cigarette Lighter',
        digitalOdometer: 'Digital Odometer',
        heightAdjustableDriverSeat: 'Height Adjustable Driver Seat',
      },
      tachometer: null,
      electronicMultiTripmeter: null,
      digitalClock: null,
      cigaretteLighter: null,
      digitalOdometer: null,
      heightAdjustableDriverSeat: null,
    },
    Exterior: {
      labels: {
        adjustableHeadlights: 'Adjustable Headlights',
        fogLightsFront: 'Fog Lights Front',
        fogLightsRear: 'Fog Lights Rear',
        exteriorRearViewMirror: 'Exterior Rear View Mirror',
        wheelCovers: 'Wheel Covers',
        alloyWheelSize: 'Alloy Wheel Size',
        roofCarrier: 'Roof Carrier',
        outsideRearViewMirrorTurnIndicators: 'Outside Rear View Mirror Turn Indicators',
      },
      adjustableHeadlights: null,
      fogLightsFront: null,
      fogLightsRear: null,
      exteriorRearViewMirror: null,
      wheelCovers: null,
      alloyWheelSize: null,
      roofCarrier: null,
      outsideRearViewMirrorTurnIndicators: null,
    },
    Safety: {
      labels: {
        antiLockBrakingSystem: 'Anti Lock Braking System',
        centralLocking: 'Central Locking',
        antiTheftAlarm: 'Anti Theft Alarm',
        noofAirbags: 'Noof Airbags',
      },
      antiLockBrakingSystem: null,
      centralLocking: null,
      antiTheftAlarm: null,
      noofAirbags: 6,
    },
    'Entertainment & Communication': {
      labels: {
        DVDPlayer: 'DVDPlayer',
        audioSystemRemoteControl: 'Audio System Remote Control',
        integrated2DINAudio: 'Integrated 2D IN Audio',
        'USB&Auxiliaryinput': 'USB & Auxiliary Input',
        bluetoothConnectivity: 'Bluetooth Connectivity',
        touchScreen: 'Touch Screen',
        connectivity: 'Connectivity',
      },
      DVDPlayer: null,
      audioSystemRemoteControl: null,
      integrated2DINAudio: null,
      'USB&Auxiliaryinput': null,
      bluetoothConnectivity: null,
      touchScreen: null,
      connectivity: 'Android Auto,Apple CarPlay,Mirror Link',
    },
  },
};
