import login from './request-handler/login';
import userRegistration from './request-handler/userRegistration';
import astrolgerRegistration from './request-handler/astrologerRegistration';
import addQuestionHelper from './request-handler/addQuestionHelper';
import fetchAppInitialData from './request-handler/fetchAppInitialData';
import paymentHandler from '../api/stripePaymentHandler';
import fetchWebInitialData from './request-handler/fetchWebInitialData';
import fetchAnsQsnTransDetails from './request-handler/fetchAnsQsnTransDetails';
import addModQuestion from './request-handler/addModQuestion';
import addAstroAnswer from './request-handler/addAstroAnswer';
import addModAnswer from './request-handler/addModAnswer';
import updateAstroProfile from './request-handler/updateAstroProfile';
import deleteUser from './request-handler/deleteUser';
import fetchReport from './request-handler/fetchReport';
import uploadImage from './request-handler/uploadImage';
import saveAppConfiguration from './request-handler/saveAppConfiguration';
import sendContactUsMessage from './request-handler/sendContactUsMessage';
import updateStarRate from './request-handler/updateStarRate';
import deleteMessage from './request-handler/deleteMessage';
import sendNotification from './request-handler/sendNotification';
import addNoteHandler from './request-handler/addNoteHandler';
import saveVedicSign from './request-handler/saveVedicSign';
import questionClarifySave from './request-handler/saveClarifyQuestion';
import addClarifyAnswer from './request-handler/addClarifyAnswer';
import saveEmployeeSalary from './request-handler/saveEmployeeSalary';
import searchUser from './request-handler/searchUser';
import cancelPostoneQuestion from './request-handler/cancelPostponeQuestion';
import postponeQuestion from './request-handler/postponeQuestion';
import deleteQuestion from './request-handler/deleteQuestion';
import logout from './request-handler/logout';
import paymentemployeeHandler from './request-handler/paymentHandler';
import fetchFreeQuestion from './request-handler/fetchFreeQuestion';

export default function (app) {
  app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Credentials', true);
    res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
    next();
  });

  app.post('/auth/login', login);
  app.post('/auth/logout', logout);
  app.post('/auth/userRegistration', userRegistration);
  app.post('/web/astrologer-registration', astrolgerRegistration);
  app.post('/web/update-astro-profile', updateAstroProfile);
  app.post('/app/addQuestion', addQuestionHelper);
  app.post('/app/payment', paymentHandler);
  app.post('/app/send-contact-us-message', sendContactUsMessage);
  app.post('/app/update-star-rate', updateStarRate);
  app.post('/app/delete-message', deleteMessage);
  app.get('/app/fetch-initial-data', fetchAppInitialData);
  app.get('/web/fetch-initial-data', fetchWebInitialData);
  app.get('/web/fetch-ans-qsn-trans-details', fetchAnsQsnTransDetails);
  app.post('/web/add-mod-question', addModQuestion);
  app.post('/web/add-astro-answer', addAstroAnswer);
  app.post('/web/add-mod-answer', addModAnswer);
  app.get('/web/delete-user', deleteUser);
  app.get('/web/fetch-report', fetchReport);
  app.post('/web/upload-image', uploadImage);
  app.post('/web/save-app-configuration', saveAppConfiguration);
  app.post('/web/send-notification', sendNotification);
  app.post('/web/add-note', addNoteHandler);
  app.post('/web/save-vedic-sign', saveVedicSign);
  app.post('/web/question-calrify-save', questionClarifySave);
  app.post('/web/add-clarify-answer', addClarifyAnswer);
  app.post('/web/save-employee-salary', saveEmployeeSalary);
  app.post('/web/search-user', searchUser);
  app.post('/web/cancel-postpone-question', cancelPostoneQuestion);
  app.post('/web/postpone-question', postponeQuestion);
  app.post('/web/delete-question', deleteQuestion);
  app.post('/web/employee-salary-payment', paymentemployeeHandler);
  app.get('/app/fetch-free-question', fetchFreeQuestion);
}
